version: '3.8'

services:
  # Сервис Django
  django:
    build:
      context: ./django_client/client/search_client  # Укажите путь к Django-проекту
    container_name: django
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - app_network  # Добавляем сеть


  # Сервис FastAPI
  fastapi:
    build:
      context: ./fastapi_sever/server_api  # Укажите путь к FastAPI-проекту
    container_name: fastapi
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DATABASE_URL=postgresql://postgres:PARol666@postgres:5432/items
    depends_on:
      - kafka
      - postgres
    networks:
      - app_network  # Добавляем сеть


  # PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PARol666
      POSTGRES_DB: items
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network  # Добавляем сеть


  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app_network  # Добавляем сеть


  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app_network  # Добавляем сеть


  # Kafka UI (опционально, для мониторинга Kafka)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - app_network  # Добавляем сеть


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge